# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John-Mike Marquardt
email: jmmarquardt@gmail.com
description:  I am an awesome front-end developer that used to be a chemist, chromatographer and engineer.
baseurl: "/codemarq.github.io" # the subpath of your site, e.g. /blog
url: "https://codemarq.github.io" # the base hostname & protocol for your site
twitter_username: Super_johnmike
github_username:  codemarq

# Build settings
markdown: sublime
